name: PlasChain
channels:
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - biopython=1.79=py37h5e8e339_1
  - blas=1.0=mkl
  - blast=2.12.0=pl5262h3289130_0
  - boost-cpp=1.74.0=h359cf19_6
  - bwa=0.7.17=h5bf99c6_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - curl=7.88.1=h37d81fd_2
  - decorator=5.1.1=pyhd3eb1b0_0
  - diamond=2.0.14
  - entrez-direct=24.0=he881be0_0
  - hmmer=3.3.2=h87f3376_2
  - icu=69.1=h9c3ff4c_0
  - infernal=1.1.4=h779adbc_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - joblib=0.14.1=py_0
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=7.88.1=h91b91d3_2
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.52.0=ha637b67_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng
  - libunistring=0.9.10=h27cfd23_0
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - mummer4=4.0.0rc1=pl5262h1b792b2_1
  - ncurses=6.4=h6a678d5_0
  - networkx=2.4=py_1
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - openssl=1.1.1w=h7f8727e_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=22.3.1=py37h06a4308_0
  - plasclass=0.1.1=pyhdfd78af_0
  - platon=1.7=pyhdfd78af_0
  - prodigal=2.6.3=hec16e2b_4
  - pthread-stubs=0.3=h0ce48e5_1
  - pysam=0.15.3=py37hbcae180_3
  - python=3.7.16=h7a1cb2a_0
  - python_abi=3.7=2_cp37m
  - readline=8.2=h5eee18b_0
  - samtools=1.6=hb116620_7
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.3.2=py37h7c811a0_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wget=1.21.4=h91b91d3_1
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13
  - zstd=1.5.5=hc292b87_0
prefix: /home/rice/anaconda3/envs/PlasChain
